spring:
  application:
    name: "configserver"
  profiles:
    active: git
  cloud:
    config: 
      server:
        git:
          uri: "https://github.com/ZevaGuillo/zevaguillo-ms-config.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
        # native:
          #search-locations: "classpath:/config"
          # search-locations: "file:///D://Guillermo//SPRING//config"
server:
  port: 8071
